<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>aquamarine</RootNamespace>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SmartReader" Version="0.11.0" />
      <PackageReference Include="System.ServiceModel.Syndication" Version="11.0.0-preview.2.26159.112" />
    </ItemGroup>

</Project>
